2023-01-16 22:45:47,436 - DEBUG    - server   - Запрос получен от ('127.0.0.1', 53984)
2023-01-16 22:45:47,438 - DEBUG    - server   - got presence
2023-01-16 22:45:47,477 - DEBUG    - server   - {"response": 200, "alert": "ok"} is sent
2023-01-16 22:45:52,440 - DEBUG    - server   - got get contacts
2023-01-16 22:45:52,453 - DEBUG    - server   - {"response": 202, "alert": ["Bob", "Thomas"]} is sent
2023-01-16 22:45:57,463 - DEBUG    - server   - got add contact
2023-01-16 22:45:57,470 - DEBUG    - server   - {"response": 400, "alert": "Already in contacts"} is sent
2023-01-16 22:46:02,482 - DEBUG    - server   - got del contact
2023-01-16 22:46:02,489 - DEBUG    - server   - {"response": 400, "alert": "Bill not in your contacts"} is sent
2023-01-16 22:46:07,492 - DEBUG    - server   - got get contacts
2023-01-16 22:46:07,503 - DEBUG    - server   - {"response": 202, "alert": ["Bob", "Thomas"]} is sent
2023-01-16 22:46:12,512 - DEBUG    - server   - got message
2023-01-16 22:46:12,729 - DEBUG    - server   - Func send_to_all(({'all': '{"action": "msg", "text": "Good bue", "time": "Mon Jan 16 22:45:47 2023", "user": {"name": "Mary", "status": "here"}, "to_user": "all"}'}, [<socket.socket fd=400, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 53984)>]), {}) was called from call
2023-01-16 22:46:12,730 - DEBUG    - server   - {"action": "msg", "text": "Good bue", "time": "Mon Jan 16 22:45:47 2023", "user": {"name": "Mary", "status": "here"}, "to_user": "all"} is sent
2023-01-16 22:46:12,730 - ERROR    - server   - Такого пользователя в чате нет
2023-01-16 22:46:27,579 - ERROR    - server   - [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
